[package]
name = "disasm_frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bitmatch = "0.1.1"
byteorder = "1.4.3"
register-bits = { version = "0.2.3", features = ["64bit"] }
